---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    user:
      name: johnd
      comment: John Doe
      uid: 1040
      group: admin
  - name: Add group "admin" to remote server
    group:
      name: admin
      gid: 2011
      state: present
  - name: Add group "developers" to remote server
    group:
      name: developers
      gid: 2012
      state: present
  - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
    user:
      name: james
      shell: /bin/bash
      groups: admin,developers
