---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
  - name: Add the user 'Nttuser1' with a specific uid and a primary group of 'Nttdata'
    user:
      name: Nttuser1
      comment: Devops Engineer
      uid: 1050
  - name: Add group "Nttdata" to remote server
    group:
      name: Nttdata
      gid: 2020
      state: present
  - name: Add the user 'Nttuser2' with a bash shell, appending the group 'Nttdata' and 'developers' to the user's groups
    user:
      name: Nttuser2
      shell: /bin/bash
  - name: Add group "developers" to remote server
    group:
      name: developers
      gid: 2021
      state: present

    
