---
- hosts: all
  become: yes
  tasks:
  - name: Installs nginx web server
    apt:
      name: nginx
      state: latest
      update_cache: true
    when: ansible_facts['distribution'] == "Ubuntu"
  - name: Installs nginx web server
    yum:
      name: nginx
      state: latest
      update_cache: true
    when: ansible_facts['distribution'] == "CentOS"
    notify:
    - start nginx
  handlers:
  - name: start nginx
    service:
      name: nginx
      state: latest
