---
- hosts: all
  become: yes
  tasks:
  - name: Installs nginx web server
    package:
      name: nginx
      state: latest
      update_cache: true
    when: (ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "Ubuntu")
    notify:
    - start nginx
  handlers:
  - name: start nginx
    service:
      name: nginx
      state: latest
